# Generated by Django 5.2.4 on 2025-07-19 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetectedPlate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_text', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('vehicle_type', models.CharField(blank=True, max_length=20, null=True)),
                ('car_image_path', models.CharField(max_length=255)),
                ('car_video_path', models.CharField(max_length=255)),
            ],
        ),
    ]
